create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  nome_cliente text not null,
  telefone text not null,
  servico text not null,
  data date not null,
  horario time not null,
  observacoes text,
  created_at timestamptz not null default now()
);

alter table public.agendamentos enable row level security;

drop policy if exists "Permitir novos agendamentos pelo site" on public.agendamentos;

create policy "Permitir novos agendamentos pelo site"
on public.agendamentos
for insert
to anon
with check (true);
